### ISSUE TITLE
Suppression de l'entrée du menu Outils

### ISSUE THREAD

**Issue by felag** [Probesys/glpi-plugins-projectbridge#17]
Une fois le plugin ProjectBridge installé, il y a une entrée de menu ProjectBridge dans le menu Outils.

Ce n'est pas utilisé et peut être soumis à mauvaise interprétation: à supprimer dans la prochaine version.

**Comment by felag** [comment]
Corrigé en version 2.7.7 avec le commit suivant: https://github.com/Probesys/glpi-plugins-projectbridge/commit/6aea715e8baae1c54ff5f3c80b1069f92a773c75

**Comment by clemparker** [comment]
Dommage nous nous servions de ce menu :( nous sommes donc obligé de rester en version 2.7.5.
ça serais bien de le remettre. Merci.

**Comment by philg38** [comment]
Bonjour @clemparker ,
Nous venons de remettre en place le menu dans la dernière release : https://github.com/Probesys/glpi-plugins-projectbridge/releases/tag/v2.7.9

**Comment by clemparker** [comment]
Bonjour,
Merci nous pourrons donc passer à la dernière version 😊

 

De : pgodot ***@***.***> 
Envoyé : mercredi 5 juin 2024 16:21
À : Probesys/glpi-plugins-projectbridge ***@***.***>
Cc : clemparker ***@***.***>; Mention ***@***.***>
Objet : Re: [Probesys/glpi-plugins-projectbridge] Suppression de l'entrée du menu Outils (Issue #17)

 

Bonjour @clemparker <https://github.com/clemparker>  ,
Nous venons de remettre en place le menu dans la dernière release : https://github.com/Probesys/glpi-plugins-projectbridge/releases/tag/v2.7.9
