### ISSUE TITLE
Add suport for localization

### ISSUE THREAD

**Issue by p-bo** [Probesys/glpi-plugins-projectbridge#2]
To be more useful for wider audience, it would be very helpful if this plugin would be possible to translate into other languages too.
Thanks :)

**Comment by felag** [comment]
Hello,
thanks for you interest in this plugin.

> To be more useful for wider audience, it would be very helpful if this plugin would be possible to translate into other languages too.

It is possible, [using locales](https://github.com/Probesys/glpi-plugins-projectbridge/tree/github/locales directory) ! :-)
(So I close this issue.)

Thanks and Regards

**Comment by p-bo** [comment]
Hello,
thanks for making plugin translatable - will do.
To which branch to make pull request - Master or Github (default)?
Or is this plugin translation managed on Transifex service, as in case of many others?

Regards

**Comment by felag** [comment]
Please make pull requests on github branch.

I have removed master branch to avoid misleading information.

Regards
PS: feel free to reopen this issue if you want to link it to your future translation commit.
