### ISSUE TITLE
9.4.1.1not compatbile

### ISSUE THREAD

**Issue by kl3sk** [Probesys/glpi-plugins-projectbridge#3]
Hello,
Any update for this ?

Thx

**Comment by prob6** [comment]
hi,
we have planned to update many of our plugins into glpi 9.4.x.
be patient please.

**Comment by kl3sk** [comment]
Hello,
Thank you for your answer, any roadmap or information about when and which one in first ?

**Comment by kl3sk** [comment]
I've made some changes (locally), plugin is installable but nothing appears on the front.

**Comment by cyrilus** [comment]
Fix with last release
