### ISSUE TITLE
Compatibility with version 9.5 of GLPI?

### ISSUE THREAD

**Issue by ozit** [Probesys/glpi-plugins-projectbridge#5]
Hello,
Are you thinking of upgrading the plugin to a version compatible with the latest version of GLPI?
thx

**Comment by prob6** [comment]
Hello @ozit,

Thank you for your interest in ProjectBridge.

>  Are you thinking of upgrading the plugin to a version compatible with the latest version of GLPI?

This is now done, see [latest release v2.2.0](https://github.com/Probesys/glpi-plugins-projectbridge/releases/tag/v2.2.0).

Regards
